Resolução da issue #6
diogosmendonca/PatternLanguage pull request #12
Opened 2020-10-27 18:52 UTC by deniscrispe

resolves #6

2020-10-27 19:09 UTC, diogosmendonca requested changes
1. 

1. 

1. A alteração está quebrando os testes. Mais especificamente o teste abaixo, conforme pode ser observado no build da pipeline:
java.lang.AssertionError: expected:<1> but was:<2>
	at scpl.AceitacaoTest.tc46(AceitacaoTest.java:586)

2. O pull request não inclui teste automatizado que mostre que o problema foi corrigido. Favor incluir.

2020-10-28 10:21 UTC, diogosmendonca commented
Explica um pouco melhor qual foi a resolução deste problema? Foi marcar a linha toda? No alerta da descrição da issue a marcação ia até a linha 30, agora vai até a 44. Qual o motivo desta diferença?

2020-10-28 12:18 UTC, deniscrispe commented
> Explica um pouco melhor qual foi a resolução deste problema? Foi marcar a linha toda? No alerta da descrição da issue a marcação ia até a linha 30, agora vai até a 44. Qual o motivo desta diferença?

Como não consigo acessar a assinatura do método, fiz uma adaptação para esses casos quando não é para retornar o método inteiro e sim apenas a sua assinatura. O início continua sendo o início do método e o fim passa a ser o início do bloco.

Exemplo:

_**public void doSomething(){**_
        syso("Test");
}

2020-10-29 17:00 UTC, diogosmendonca commented
Oi Denis, foi uma boa solução encontrada. Vou fazer o merge.

2020-10-29 17:00 UTC, merged